### ISSUE TITLE
Cuda Out-Of-Memory Problem When Doing Federated Training On Own Desiged Model

### ISSUE THREAD

**Issue by giantke** [liuquande/FedIRM#4]
Thanks a lot for sharing your codes. I have a question about federated training: 
I applied this codes to my own designed model(four RTX 2080TI were used in this task). When I use DataParallel to train, there will be serious load imbalance, so I use DistributedDataParallel for training. However, since the federation learning have to copy multiple models(eg., 10 times) to the GPU, and the models are back propagated separately, it will lead to the problem of cuda out-of-memory (in fact, I will also encounter this OOM problem when I use DP). Do you encounter such a problem like me and how to solve it if so?

**Comment by HongzhengYang** [comment]
Thanks for your interest in our work. I did not encounter such problems. Have you further modified the code downloaded from this repository ?
